services:
  postgres:
    image: postgres:15
    container_name: diyou_db
    environment:
      POSTGRES_DB: diyou_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/tmp/scripts